# Generated by Django 6.0.7 on 2026-07-15 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_product_adminpordect_userpordect'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adminpordect',
            new_name='Adminporduct',
        ),
    ]
