# Generated by Django 6.0.7 on 2026-07-16 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_merchant_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=10)),
                ('profile', models.ImageField(upload_to='merchant/profile/')),
                ('aadhaar', models.CharField(max_length=12)),
                ('aadhaar_file', models.FileField(upload_to='merchant/aadhaar/')),
                ('pan', models.CharField(max_length=10)),
                ('pan_file', models.FileField(upload_to='merchant/pan/')),
                ('account_holder', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=30)),
                ('ifsc', models.CharField(max_length=11)),
                ('passbook', models.FileField(upload_to='merchant/passbook/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
